### ISSUE TITLE
(Linux) Crash when selecting "add" in skript addons

### ISSUE THREAD

**Issue by CroissantDuNord** [SkEditorPlus/SkAnalyzer#1]
**System Info:**
Fedora Linux 39 (KDE Plasma) (6.6.7-200)
Intel i5-9400F (6) @ 4.100GHz + NVIDIA GeForce GTX 1650 

**This is the error:**
![image](https://github.com/SkEditorTeam/SkAnalyzer/assets/79372025/c8be5052-711f-4589-a099-7eb52e956914)

**This is what was selected:**
![image](https://github.com/SkEditorTeam/SkAnalyzer/assets/79372025/02ffe458-49a5-4cce-8639-b97c52726f94)

**Comment by NotroDev** [comment]
Hmmm.
The error message seems incorrect.
Maybe there is some incompability with Linux, because on Windows it works fine.

Can you check if you have logs?
I don't know where is the SkEditor's folder on Linux, but you should be able to open it by going into Settings -> Personalization -> Theme and clicking "Open Folder".
Then just return to root SkEditor folder and enter the Logs folder.

**Comment by CroissantDuNord** [comment]
Oh yeah, this seem more correct

```
2024-01-08 21:56:42.865 +01:00 [FTL] Application crashed!
Tmds.DBus.Protocol.DBusException: org.freedesktop.portal.Error.InvalidArgument: invalid filter: name is empty
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync[T](MessageBuffer message, MessageValueReader`1 valueReader, Object state)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync[T](MessageBuffer message, MessageValueReader`1 reader, Object readerState)
   at Avalonia.FreeDesktop.DBusSystemDialog.OpenFilePickerAsync(FilePickerOpenOptions options)
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.OpenFilePickerAsync(FilePickerOpenOptions options)
   at AnalyzerAddon.Views.AnalyzerAddonsSettingsPage.AddAddons()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state) in /_/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1914
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at SkEditor.Desktop.Program.Main(String[] args)
```

[log-202401082156.txt](https://github.com/SkEditorTeam/SkAnalyzer/files/13866197/log-202401082156.txt)

**Comment by NotroDev** [comment]
Hmm, interesting.
@GliczDev can you look at it?
