### ISSUE TITLE
SkAnalyzer crashes the editor brutaly when not loaded

### ISSUE THREAD

**Issue by ScienceKit** [SkEditorPlus/SkAnalyzer#2]
So when I haven't loaded the analyser, and I am writing my skript the addon crashes the editor, when i use a generator be it default gen or addon generator. I figured it is bcause there is no check if the analyser is loaded when i use the generator. I can confirm this with the logs.

It is important to note I am on windows 11. I have tested this with a band new instalation of the editor with 0 outside-marketplace 
 addons installed. The log is from that editor. The structure of the crash is also wierd as it crahses then briefly opens a new window and crashing it instantly. Prob why we got 2 crashes in the same log.

```
2024-01-21 10:18:48.886 +02:00 [FTL] Application crashed!
System.NullReferenceException: Object reference not set to an instance of an object.
   at AnalyzerAddon.Analyzing.Analyzer.Analyze()
   at AnalyzerAddon.AnalyzerAddon.<>c.<<CheckForAnalyze>b__7_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at SkEditor.Desktop.Program.Main(String[] args)
2024-01-21 10:18:50.650 +02:00 [FTL] Application crashed!
System.NullReferenceException: Object reference not set to an instance of an object.
   at SkEditor.Utilities.Syntax.SyntaxLoader.RefreshSyntaxAsync(String extension)
   at SkEditor.Utilities.Syntax.SyntaxLoader.LoadAdvancedSyntaxes()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32DispatcherImpl.DispatchWorkItem()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at SkEditor.Desktop.Program.Main(String[] args)
```

**Comment by NotroDev** [comment]
It should be fixed now, please update SkEditor and Analyzer :)
